### ISSUE TITLE
somePushTokens is not defined

### ISSUE THREAD

**Issue by gregbenner** [expo/exponent-server-sdk-node#11]
is this a working demo?

**Comment by gregbenner** [comment]
https://github.com/expo/expo-server-sdk-ruby
https://github.com/expo/expo-server-sdk-python
Are broken links also

**Comment by MyGuySi** [comment]
You need to define `somePushTokens` yourself if you're testing, it's just an array of access token strings. In production you'd probably have those stored on your server somewhere.

See: https://docs.expo.io/versions/latest/guides/push-notifications.html

**Comment by gregbenner** [comment]
Oh I thought the server would return one, we can make our own, so I can just write ExponentPushToken['someuniquestring'] and push a few of these into an array `somePushTokens` in this example?
