### ISSUE TITLE
TypeError: expo_server_sdk_1.default is not a constructor

### ISSUE THREAD

**Issue by matheuschagas** [expo/exponent-server-sdk-node#16]
I used yarn to install the exponent-server-sdk-node and run a test just as the README says...but I got this error:

> Error: Error occurred while parsing your function triggers.
>
>TypeError: expo_server_sdk_1.default is not a constructor
>    at Object.<anonymous> (/tmp/fbfn_70529Pawxah2ftqq/lib/index.js:16:12)
>    at Module._compile (module.js:641:30)
>    at Object.Module._extensions..js (module.js:652:10)
>    at Module.load (module.js:560:32)
>    at tryModuleLoad (module.js:503:12)
>    at Function.Module._load (module.js:495:3)
>    at Module.require (module.js:585:17)
>    at require (internal/module.js:11:18)
>    at /usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:18:11
>    at Object.<anonymous> (/usr/local/lib/node_modules/firebase-tools/lib/triggerParser.js:32:3)

My node version is 9.2.1

**Comment by ide** [comment]
It looks like this error is related to your development environment. Have you tried this in a brand new, plain Node project without Firebase (I see that in your stack trace) or any other packages? `expo_server_sdk_1` is nowhere in the published JS, so it's likely coming from something on your computer:

```
$ cd /tmp/
$ npm view expo-server-sdk dist.tarball
https://registry.npmjs.org/expo-server-sdk/-/expo-server-sdk-2.3.3.tgz
$ wget https://registry.npmjs.org/expo-server-sdk/-/expo-server-sdk-2.3.3.tgz
--2018-01-03 12:11:30--  https://registry.npmjs.org/expo-server-sdk/-/expo-server-sdk-2.3.3.tgz
Resolving registry.npmjs.org (registry.npmjs.org)... 151.101.188.162
Connecting to registry.npmjs.org (registry.npmjs.org)|151.101.188.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10281 (10K) [application/octet-stream]
Saving to: ‘expo-server-sdk-2.3.3.tgz’

expo-server-sdk-2.3.3.tg 100%[==================================>]  10.04K  --.-KB/s    in 0.001s  

2018-01-03 12:11:30 (18.3 MB/s) - ‘expo-server-sdk-2.3.3.tgz’ saved [10281/10281]
$ mkdir expo-server-sdk
$ tar -xzf expo-server-sdk-2.3.3.tgz -C expo-server-sdk
$ grep -r expo_server_sdk_1 expo-server-sdk
```
