### ISSUE TITLE
2 npm packages = confusing

### ISSUE THREAD

**Issue by JulianKingman** [expo/exponent-server-sdk-node#4]
I noticed both of these packages on NPM, which is the correct one?
https://www.npmjs.com/package/expo-server-sdk
https://www.npmjs.com/package/exponent-server-sdk

I would guess the first one, but it's at a lower version number.

**Comment by ide** [comment]
We're planning to move to the first one and will put a deprecation message on the latter, thanks for raising this.

**Comment by ide** [comment]
This package is now published under the name `expo-server-sdk` and the old package (`exponent-server-sdk`) has a deprecation message on it.
