### ISSUE TITLE
server code hangs

### ISSUE THREAD

**Issue by abhitheawesomecoder** [expo/exponent-server-sdk-node#5]
my code is getting stuck at 

import Expo from 'exponent-server-sdk';

when i execute my index file like this ./index.js

with code 

import Expo from 'exponent-server-sdk';

it never returns back

**Comment by ashishd751** [comment]
@abhitheawesomecoder I am facing the same error... Apparently, there is no class/function with the name Expo being exported from 'exponent-server-sdk' module. 
There is already a class named Expo in the 'expo' module that was first installed using npm.
And why are there 2 libraries with the same functionality and a different name! Utterly confusing!
@abi Unable to proceed, please help.

**Comment by dikaiosune** [comment]
@abhitheawesomecoder are you sure you have the package installed?

@ashishd751 it sounds like you're trying to load this within your Expo app -- this library is only for use on your server.

**Comment by ide** [comment]
Closing this since we haven't heard back and don't have enough information.
