### ISSUE TITLE
Having Trouble Implementing Code w Firebase Cloud Functions

### ISSUE THREAD

**Issue by varunkhurana9999** [expo/exponent-server-sdk-node#7]
Hey, I'm trying to set up push notifications with Firebase Cloud Functions, which certainly isn't ideal but trying to make it work. Cloud Functions uses Node LTS 6.11 w no built in async await so I'm using the async await library. I'm pretty new to node and my use case is for a single notification and I tried to split the push to expo backend from the rest of the function.

 I keep getting either await expo.sendPushNotificationsAsync(chunk); SyntaxError: Unexpected identifier in regards to the 'expo'

Here's my code, would love to know if it's something wrong on my part or the implementation between cloud functions and expo's system. Code attached for reference 

<img width="899" alt="screen shot 2017-08-21 at 2 49 29 am" src="https://user-images.githubusercontent.com/4992940/29506788-614748d4-861b-11e7-8721-059c1d8df8dd.png">

<img width="635" alt="screen shot 2017-08-21 at 2 49 52 am" src="https://user-images.githubusercontent.com/4992940/29506798-6dd756d4-861b-11e7-9198-7d6b8857b99a.png">

**Comment by dikaiosune** [comment]
It looks like you're trying to use `await` on the 4th line of the second screenshot here -- which won't work on older versions of Node. It's just a promise, I'd recommend reading [the MDN page on Promises in JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) for how to interact with it.
